SELECT TBR.RUT_TRABAJADOR, TBR.NOMBRE_TRABAJADOR, LMED.MONTO_REEMBOLSO,
	(SELECT TMET.VALUE
		FROM TBL_METADATOS TMET
		WHERE LMED.ID_LICENCIA_MEDICA = TMET.ID_LICENCIA_MEDICA
        AND TMET.[KEY] = 'renta1') 'Renta 1',
	(SELECT TMET.VALUE
		FROM TBL_METADATOS TMET 
		WHERE LMED.ID_LICENCIA_MEDICA = TMET.ID_LICENCIA_MEDICA
        AND TMET.[KEY] = 'renta2') 'Renta 2',
	(SELECT TMET.VALUE
		FROM TBL_METADATOS TMET 
		WHERE LMED.ID_LICENCIA_MEDICA = TMET.ID_LICENCIA_MEDICA
        AND TMET.[KEY] = 'renta3') 'Renta 3'
FROM TBL_TRABAJADOR TBR
INNER JOIN REL_TRABAJADOR_EMPRESA RTBRE ON
RTBRE.ID_TRABAJADOR = TBR.ID_TRABAJADOR
INNER JOIN TBL_LICENCIA_MEDICA LMED ON
LMED.ID_TRABAJADOR_EMPRESA = RTBRE.ID_TRABAJADOR_EMPRESA
INNER JOIN TBL_METADATOS TMET2 ON
TMET2.ID_LICENCIA_MEDICA = LMED.ID_LICENCIA_MEDICA
WHERE format(LMED.FECHA_FIN,'yyyy-MM-dd') >= format(getdate(),'yyyy-MM-dd')
GROUP BY TBR.RUT_TRABAJADOR, TBR.NOMBRE_TRABAJADOR, LMED.MONTO_REEMBOLSO, LMED.ID_LICENCIA_MEDICA;
