select emp.NOMBRE_EMPRESA, emp.RUT_EMPRESA
from TBL_EMPRESA emp
INNER JOIN REL_TRABAJADOR_EMPRESA rtrbe on
emp.ID_EMPRESA = rtrbe.ID_EMPRESA
INNER JOIN TBL_LICENCIA_MEDICA lmed on
lmed.ID_TRABAJADOR_EMPRESA = rtrbe.ID_TRABAJADOR_EMPRESA
where rtrbe.FECHA_FIN_CONTRATO <> '9999-12-30 00:00:00.000';
