SELECT EMP.RUT_EMPRESA, EMP.NOMBRE_EMPRESA, format(avg(CAST(TMET.VALUE as int)),'###,###','de-de') "Promedio renta"
FROM TBL_EMPRESA EMP
INNER JOIN REL_TRABAJADOR_EMPRESA RTBRE ON
RTBRE.ID_EMPRESA = EMP.ID_EMPRESA
INNER JOIN TBL_LICENCIA_MEDICA LMED ON
LMED.ID_TRABAJADOR_EMPRESA = RTBRE.ID_TRABAJADOR_EMPRESA
INNER JOIN TBL_METADATOS TMET ON
TMET.ID_LICENCIA_MEDICA = LMED.ID_LICENCIA_MEDICA
GROUP BY EMP.RUT_EMPRESA, EMP.NOMBRE_EMPRESA;