SELECT TBR.RUT_TRABAJADOR, TBR.NOMBRE_TRABAJADOR, COUNT(1)+1 "Cantidad licencias"
FROM TBL_TRABAJADOR TBR
INNER JOIN REL_TRABAJADOR_EMPRESA RTBRE 
ON TBR.ID_TRABAJADOR = RTBRE.ID_TRABAJADOR
INNER JOIN TBL_LICENCIA_MEDICA LMED 
ON RTBRE.ID_TRABAJADOR_EMPRESA = LMED.ID_TRABAJADOR_EMPRESA
WHERE RTBRE.FECHA_FIN_CONTRATO > GETDATE()
AND format(LMED.FECHA_INICIO,'yyyy') >= format(getdate(),'yyyy')
AND format(LMED.FECHA_FIN,'yyyy') <= format(getdate(),'yyyy')
AND EXISTS (SELECT 1 FROM TBL_LICENCIA_MEDICA AS lm2 
            WHERE LMED.ID_TRABAJADOR_EMPRESA = lm2.ID_TRABAJADOR_EMPRESA 
            AND lm2.FECHA_INICIO = LMED.FECHA_FIN + 1
            AND lm2.FECHA_FIN-lm2.FECHA_INICIO <=15)
GROUP BY TBR.RUT_TRABAJADOR, TBR.NOMBRE_TRABAJADOR;