SELECT TEMPRESA.NOMBRE_EMPRESA, TRAB.RUT_TRABAJADOR, TRAB.NOMBRE_TRABAJADOR, TLIC.MONTO_REEMBOLSO, ROW_NUMBER() OVER(PARTITION BY TEMPRESA.ID_EMPRESA ORDER BY TLIC.MONTO_REEMBOLSO DESC) AS Posicion
FROM TBL_EMPRESA TEMPRESA
INNER JOIN REL_TRABAJADOR_EMPRESA TEMPRE ON
TEMPRE.ID_EMPRESA = TEMPRESA.ID_EMPRESA
INNER JOIN TBL_LICENCIA_MEDICA TLIC ON
TLIC.ID_TRABAJADOR_EMPRESA = TEMPRE.ID_TRABAJADOR_EMPRESA
INNER JOIN TBL_TRABAJADOR TRAB ON
TRAB.ID_TRABAJADOR = TEMPRE.ID_TRABAJADOR
WHERE TLIC.ID_LICENCIA_MEDICA IN (SELECT b.ID_LICENCIA_MEDICA
                            FROM REL_TRABAJADOR_EMPRESA a
                            INNER JOIN TBL_LICENCIA_MEDICA b ON 
                            a.id_trabajador_empresa = b.id_trabajador_empresa
                            WHERE TEMPRESA.id_empresa = a.id_empresa
                            ORDER BY b.MONTO_REEMBOLSO DESC OFFSET 0 ROWS FETCH FIRST 3 ROWS ONLY)
ORDER BY TEMPRESA.ID_EMPRESA ASC, TLIC.MONTO_REEMBOLSO DESC;